In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
df = pd.read_excel("Rolling data.xlsx")

In [2]:
import scipy.stats as sm

In [3]:
df.columns

Index(['ReheatingTime', 'RollDia', 'RollCrown', 'EntryThickness', 'Width',
       'Length', 'Temperature', 'Speed', 'WaitTime', 'Redn', 'Strain',
       'strainrate', 'Flowstress ', 'Force', 'Torque'],
      dtype='object')

In [28]:
from scipy import stats
column=list(df.columns)
mu = []
S = []
xbar = []
t_value = []
half_p_value = []
half_alpha_value=[]
for i in column:
    df1 = df[i]
    df2 = df1.loc[df1 != 0]
    
    a = df2.to_numpy()
    mu.append(a.mean())
    S.append(a.std())
    
    b = np.random.choice(a, 150, replace=False)
    b1 = np.mean(b)


    c = np.random.choice(a, 150, replace=False)
    c1 = np.mean(c)


    d = np.random.choice(a, 150, replace=False)
    d1 = np.mean(d)
  

    e = np.random.choice(a, 150, replace=False)
    e1 = np.mean(e)
 

    f = np.random.choice(a, 150, replace=False)
    f1 = np.mean(f)
  
    xbar.append((b1+c1+d1+e1+f1)/5)
    alpha=0.025
    half_alpha_value.append((alpha))

for item1,item2,item3 in zip(mu,S,xbar):
    t_value.append(((item3-item1)/(item2/np.sqrt(150))))
#for i in t_value:
 #   if i>0:
  #    half_p_value.append((1-stats.t.cdf(x=t_value,df=149)))
    #if i<0:
        #half_p_value.append((stats.t.cdf(x=t_value,df=149)))

print(mu)
print(sigma)
print(xbar)
print(t_value)
print(half_p_value)
print(half_alpha_value)

[257.8340206185567, 1079.8878659793813, 88.58680412371132, 132.4364948453608, 2625.9777216494845, 8097.288659793814, 1085.5721649484535, 2.1649793814432985, 23.631958762886597, 0.1600618556701031, 0.20598074380206188, 4.336921773662887, 78.55407675309277, 29050.963917525773, 3169.239175257732]
[109.86091618247676, 28.81949678214131, 67.59779106447698, 75.21025445467241, 504.04161279106245, 7383.006642253691, 81.03963296935545, 0.7146166513157678, 32.634742243778895, 0.0698850033959309, 0.0996734812780645, 3.3673572847640294, 28.59513087573856, 8098.057862351752, 1252.4065026778787, 109.86091618247676, 28.81949678214131, 67.59779106447698, 75.21025445467241, 504.04161279106245, 7383.006642253691, 81.03963296935545, 0.7146166513157678, 32.634742243778895, 0.0698850033959309, 0.0996734812780645, 3.3673572847640294, 28.59513087573856, 8098.057862351752, 1252.4065026778787]
[259.1973333333334, 1079.6105733333334, 86.21106666666665, 131.36927999999997, 2627.6478533333334, 8595.857333333333, 1085.92, 2.1891999999999996, 24.28666666666667, 0.159, 0.20678086406533333, 4.435189258257333, 78.78154680364, 29382.952, 3137.1000000000004]
[0.15198400974122442, -0.11784131717812779, -0.430438956727596, -0.17378825773238057, 0.04058167346572771, 0.8270606482451163, 0.052568006525024955, 0.41510477407199337, 0.24570445245880124, -0.18609175401321573, 0.098315336875251, 0.3574096468056665, 0.09742664896815384, 0.5020965622680283, -0.31429324251749075]
[]
[0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025]

In [30]:
Data={'mu':mu,
      "S":S,
      'xbar':xbar,
      't_value calculated':t_value,
      #'half_p_value':half_p_value,
      #'half_alpha_value':half_alpha_value
      "t_value for 0.025,149":'+/- 1.97'
     }
dataframe = pd.DataFrame(Data)
dataframe

,mu,S,xbar,t_value calculated,"t_value for 0.025,149"
0,257.834021,109.860916,259.197333,0.151984,+/- 1.97
1,1079.887866,28.819497,1079.610573,-0.117841,+/- 1.97
2,88.586804,67.597791,86.211067,-0.430439,+/- 1.97
3,132.436495,75.210254,131.369280,-0.173788,+/- 1.97
4,2625.977722,504.041613,2627.647853,0.040582,+/- 1.97
5,8097.288660,7383.006642,8595.857333,0.827061,+/- 1.97
6,1085.572165,81.039633,1085.920000,0.052568,+/- 1.97
7,2.164979,0.714617,2.189200,0.415105,+/- 1.97
8,23.631959,32.634742,24.286667,0.245704,+/- 1.97
9,0.160062,0.069885,0.159000,-0.186092,+/- 1.97
10,0.205981,0.099673,0.206781,0.098315,+/- 1.97
11,4.336922,3.367357,4.435189,0.357410,+/- 1.97
12,78.554077,28.595131,78.781547,0.097427,+/- 1.97
13,29050.963918,8098.057862,29382.952000,0.502097,+/- 1.97
14,3169.239175,1252.406503,3137.100000,-0.314293,+/- 1.97